import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Intro = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Intro | Weird Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ℹ️ Intro</h1>
        <br />
        <h2 className={styles.title}>Aturan dalam Game 🎮</h2>
        <br />
        <br />

        <p className={styles.title}>
          Aturanya cukup sederhana, kamu hanya perlu membaca pesan / quotes
          sampai selesai,
        </p>
        <br />
        <p className={styles.title}>
          Kemudian jawab pertanyaan Essay yang disediakan, pastikan jawaban kamu
          benar. Karena kalau salah kamu tidak akan bisa lanjut ke tahap
          berikutnya.
        </p>

        <br />
        <br />
        <p className={styles.title}>Setuju?</p>
        <br />
        <Link href="/love1">
          <button type="button" className="btn btn-success">
            Baiklah aku setuju
          </button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <p className={styles.footerTxt}>dibuat dengan ❤️ oleh @panjiggm</p>
      </footer>
    </div>
  );
};

export default Intro;
