import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const summary = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Summary | Weird Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>#Summary</h1>

        <br />
        <br />

        <h2 className={styles.quotes}>✨ Selamat ✨</h2>
        <h5 className={styles.title}>
          Kamu telah berhasil menjawab semua pertanyaan dengan benar,
        </h5>

        <br />
        <div>
          {listWnswer.map((item) => (
            <h6 key={item.id}>
              <b>
                #{item.id} <span className="text-primary">{item.answer}</span>
              </b>
            </h6>
          ))}
        </div>

        <br />
        <br />
        <h6 className={styles.title}>
          Terimaksih Kiki sudah bersedia berpartisipasi 😇
        </h6>
        <br />
        <br />
        <Link href="/final">
          <button type="button" className="btn btn-success">
            One more thing
          </button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <p className={styles.footerTxt}>dibuat dengan ❤️ oleh @panjiggm</p>
      </footer>
    </div>
  );
};

export default summary;

const listWnswer = [
  {
    id: 1,
    answer: "Panji Gumelar",
  },
  {
    id: 2,
    answer: "Ciamis",
  },
  {
    id: 3,
    answer: "Tigaraksa",
  },
  {
    id: 4,
    answer: "Juli",
  },
  {
    id: 5,
    answer: "Barat",
  },
  {
    id: 6,
    answer: "172",
  },
  {
    id: 7,
    answer: "Kucing",
  },
];
